# Monta as Sprints 1 a 8 do Observatorio das Estrelas Quebradas a partir do ponto atual.
function observatorio_estrelas_quebradas/init
function observatorio_estrelas_quebradas/sprint1_blocagem
function observatorio_estrelas_quebradas/sprint2_entrada_patio
function observatorio_estrelas_quebradas/sprint3_torre_telescopio
function observatorio_estrelas_quebradas/sprint4_cupulas_constelacoes
function observatorio_estrelas_quebradas/sprint5_calculos_celestes
function observatorio_estrelas_quebradas/sprint6_planetario_arquivo
function observatorio_estrelas_quebradas/sprint7_nucleo_final
function observatorio_estrelas_quebradas/sprint8_polimento_validacao
